### ISSUE TITLE
Object name instead of edges & node in query

### ISSUE THREAD

**Issue by nerdyator** [graphql-python/graphene#731] opened 2018-05-23 07:44 UTC
![image](https://user-images.githubusercontent.com/4137219/40410144-9abc7dbc-5e8a-11e8-9708-564fdedbb89f.png)

As seen in the image, 
` allFilms(first:5) {
    films {
      title
      episodeID
      director
      producers
      characterConnection {
        totalCount
      }
    }
  }`

**allFilms** get object of **films**, but In my case I couldn't able to achieve this behaviour.

In my case I need to make use of **edges & node** to achieve same query. 
How to get this done.

Thanks in advance.

**Comment by jkimbo** [comment] 2018-05-25 15:42
@nerdyator I'm not sure I understand what the issue is exactly. What are you trying to achieve?

If you want to setup a Relay **connection** (in the format of how relay expects them: https://facebook.github.io/relay/graphql/connections.htm) then you can use the `graphene.relay.Connection` class: http://docs.graphene-python.org/en/latest/relay/connection/

**Comment by jkimbo** [comment] 2018-08-27 11:36
@nerdyator I'm going to close this issue for now. If you can provide more info on the problem you are having then I'll happily reopen it.

**Closed by jkimbo** 2018-08-27 11:36 UTC
Labels: 👀 more info needed
