### ISSUE TITLE
Name argument ignored in NodeField (Relay)

### ISSUE THREAD

**Issue by lucas-bremond** [graphql-python/graphene#1083] opened 2019-10-11 19:58 UTC
Looking at the `node.py` implementation:

```py
class NodeField(Field):
    def __init__(self, node, type=False, deprecation_reason=None, name=None, **kwargs):
        assert issubclass(node, Node), "NodeField can only operate in Nodes"
        self.node_type = node
        self.field_type = type

        super(NodeField, self).__init__(
            # If we don's specify a type, the field type will be the node
            # interface
            type or node,
            description="The ID of the object",
            id=ID(required=True),
        )
```

the `name` argument is not passed to the super class.

Which means that:

```
CustomNode.Field(
        name = 'myCustomTypeName',
        type = MyCustomType,
        filterset_class = filters.MyCustomTypeFilter
)
```

does not create a `myCustomTypeName` type, but uses the default name.

Is there any reason for this?

**Comment by BossGrand** [comment] 2019-10-31 18:46
Looks like a bug to me

**Comment by j123b567** [comment] 2020-12-16 09:45
This is probably duplicate of #1035 but because it is still not released, it is issue for graphene v2.x

**Comment by tcleonard** [comment] 2021-01-26 14:22
> This is probably duplicate of #1035 but because it is still not released, it is issue for graphene v2.x

This is indeed the same thing... I'm going to request to have it merged into the v2 branch as well as other librairies are still depending on the v2

**Comment by erikwrede** [comment] 2024-11-09 20:46
Fixed in Graphene v3, for now, no further v2 port is planned

**Closed by erikwrede** 2024-11-09 20:46 UTC
Labels: 🐛 bug
