### ISSUE TITLE
Test upload file

### ISSUE THREAD

**Issue by ckristhoff** [graphql-python/graphene#880] opened 2018-12-23 03:39 UTC
Hi grapheners
I'm making test cases for my Graphql API. Actually I test it with Insomnia and it works, but I don't know how to make a test case with it.

My mutation
```python
class AddImagesToPost(relay.ClientIDMutation):

    post = graphene.Field(PostNode)

    class Input:
        id = graphene.Argument(graphene.ID, required=True)
        images = graphene.Argument(
            graphene.List(ImageCreateMutationInput),
            required=True
        )

    @classmethod
    def mutate_and_get_payload(cls, root, info, **input):
        post_relay_id = input.get("id")
        post_model_id = from_global_id(post_relay_id)[1]
        post_instance = Post.objects.get(id=post_model_id)
        if post_instance:
            images = input.get("images")
            if info.context.FILES and images:
                for image_data in images:
                    image = Image(
                        post=post_instance,
                        principal=image_data.principal,
                        image_file=info.context.FILES[image_data.image_file]
                    )
                    image.full_clean()
                    image.save()
                return cls(post=post_instance)
            else:
                raise IndexError("Use valid images.")
        raise Post.DoesNotExist
```

Test Case
```python
def test_add_images_to_Post(self):
        query_string = """
            mutation($input: AddImagesToPostInput!){
                addImagesToPost(input: $input){
                    post{
                        name
                    }
                }
            }
        """
        variables = {
            "input": {
                "id": "TmV3c05vZGU6MQ==",
                "images": [
                    {
                        "principal": True,
                        "imageFile": "img1.png"
                    },
                    {
                        "principal": False,
                        "imageFile": "img2.png"
                    }
                ]
            }
        }
        context = {
            "img1.jpg": tempfile.NamedTemporaryFile(suffix=".jpg"),
             "img2.jpg": tempfile.NamedTemporaryFile(suffix=".jpg")
        }
        query_result = self.client.execute(
            query_string,
            context=context,
            variables=variables,
        )
        expected_result = {
            "post": OrderedDict({
                "name": "Post 1"
            })
        }
        self.assertEqual(dict(query_result.data), expected_result)
```

According to documentation context parameter should work.

**Comment by jkimbo** [comment] 2018-12-28 10:09
@ckristhoff it looks like you're grabbing `FILES` from the `context` object so it's probably a request object. You'll need to replicate that in your test case as well (or at least create a mock object with a `FILES` property)

**Comment by ckristhoff** [comment] 2019-01-05 19:53
Thank you @jkimbo for you answer
I'm grabbing the files from `FILES` in `context` just like you said. It's the way recommended by graphene at https://docs.graphene-python.org/en/latest/relay/mutations/#accepting-files.

In my test case I'm using the `Client` class recommended by Graphene doc at https://docs.graphene-python.org/en/latest/testing/#testing-in-graphene. But I'm does not achieve add files to the client graphene GraphQL mutation request.🤔

**Comment by jkimbo** [comment] 2019-01-06 18:14
@ckristhoff in your example code you're passing the context in the test as a dictionary:

```python
context = {
	"img1.jpg": tempfile.NamedTemporaryFile(suffix=".jpg"),
    "img2.jpg": tempfile.NamedTemporaryFile(suffix=".jpg")
}
```

That context needs to be the same as a Django request object (I'm assuming you're using Django) for it to work. You can use the [`RequestFactory`](https://docs.djangoproject.com/en/dev/topics/testing/advanced/#the-request-factory) to get an object that will match what you need.

If that still doesn't work then if you could create a simple reproduction of the issue that would help a lot.

**Comment by ckristhoff** [comment] 2019-01-08 00:02
Here a test repo.
https://github.com/ckristhoff/graphene-test-uploads

**Comment by jkimbo** [comment] 2019-03-10 14:21
@ckristhoff I created a fix here: https://github.com/ckristhoff/graphene-test-uploads/pull/1

I’m going to close this issue now. If you are still having problems add a comment and I can reopen it.

**Closed by jkimbo** 2019-03-10 14:21 UTC
Labels: 👀 more info needed

**Comment by elcolie** [comment] 2024-09-06 05:07
> Here a test repo. https://github.com/ckristhoff/graphene-test-uploads

Page not found

**Comment by elcolie** [comment] 2024-09-06 05:10
Hi. I need some help with gql uploading a single file.
https://stackoverflow.com/questions/78955683/need-example-of-pytest-test-upload-file-to-graphql
