### ISSUE TITLE
PyCharm warning: Expected type 'ObjectType', got 'Type[Query]' instead

### ISSUE THREAD

**Issue by denizdogan** [graphql-python/graphene#1100] opened 2019-11-22 11:40 UTC
```py

class Query(graphene.ObjectType):
    # ...

schema = Schema(query=Query)

```

![image](https://user-images.githubusercontent.com/50928/69422797-eb8b9a80-0d24-11ea-9eaf-463bd027aa03.png)

Related to #814 which was automatically closed due to staleness.

Any ideas?

**Comment by KingDarBoja** [comment] 2019-11-29 14:58
Hello @denizdogan 

What PyCharm version do you own?

**Comment by denizdogan** [comment] 2019-11-29 19:17
@KingDarBoja I use PyCharm 2019.2.4 Professional Edition

**Comment by KingDarBoja** [comment] 2019-12-05 13:20
I can confirm such behaviour on my PyCharm too;

![Warning Query Type PyCharm GraphQL](https://user-images.githubusercontent.com/30560560/70238775-f89e8580-1737-11ea-81cc-1ce26e8545fa.png)

**More info:**
```
PyCharm 2019.2.5 (Community Edition)
Build #PC-192.7142.56, built on November 19, 2019
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 976M
Cores: 4
Registry: 
Non-Bundled Plugins: org.intellij.plugins.markdown, Docker
```

**Comment by denizdogan** [comment] 2020-03-04 14:01
Don't automatically close this please

**Comment by KingDarBoja** [comment] 2020-03-08 15:14
@denizdogan Looks like the issue got solved but will be released on Graphene v3-alpha versions instead of v2, just saying, the final word is under Graphql-Python Team 😄

**Comment by tmladek** [comment] 2020-04-22 21:31
Still present, any news?

**Comment by AndHam89** [comment] 2020-04-30 15:22
I can confirm that this is still present in 2020.1 professional. It would be helpful it it gets solved.

**Comment by formigone** [comment] 2020-04-30 17:22
Came across this looking for the same PyCharm warning, but in a different situation. I'm not a user of this repo, so I won't take the time to locate the code and PR the simple fix for it.

TL/DR:

Whenever you see PyCharm complain with 

```
Expected type X, got Type[X] instead
```

that's a possible type hinting misunderstanding. [See this for more information](https://stackoverflow.com/a/44664064/774907).

In summary:

```python
# Wrong
class Schema:
   def __init__(self, query: MyClass):

# Right
from typing import Type

class Schema:
   def __init__(self, query: Type[MyClass]):
```

**Comment by AndHam89** [comment] 2020-05-01 07:24
Thanks for the hint. I changed the type specification and PyCharm does not anymore complain about a type mismatch. Thanks formigone.

**Comment by tobiasfeil** [comment] 2020-06-13 07:53
@AndHam89 Where did you change the type specification? In the source of graphene? It's still complaining for me

**Comment by AndHam89** [comment] 2020-06-13 09:32
@tobiasfeil  You need to change your type specification in you Python code as formigone pointed out. If you refer to the type of a class you need to use the syntax Type[MyClass] if you have a parameter which is of type MyClass.

**Comment by tobiasfeil** [comment] 2020-06-14 08:01
Thank you for the reply! I'm sorry I still don't understand how to do this, since I'm not defining the class `Schema` in my own code. All I'm doing is using `graphene.Schema`:
![image](https://user-images.githubusercontent.com/17533713/84588223-d9d72500-ae25-11ea-8fc8-50cf67e5c550.png)
So I don't know where the type hint should go, since there's no `class Schema` in my code... Would you be so kind to tell me how you accomplished this? Did you subclass `graphene.Schema`? Thanks in advance :)

**Comment by Abhi904485** [comment] 2020-09-07 03:30
> Thank you for the reply! I'm sorry I still don't understand how to do this, since I'm not defining the class `Schema` in my own code. All I'm doing is using `graphene.Schema`:
> ![image](https://user-images.githubusercontent.com/17533713/84588223-d9d72500-ae25-11ea-8fc8-50cf67e5c550.png)
> So I don't know where the type hint should go, since there's no `class Schema` in my code... Would you be so kind to tell me how you accomplished this? Did you subclass `graphene.Schema`? Thanks in advance :)

change the doc present in graphene/types/schema.py

Args:
        query (Type[ObjectType]): Root query *ObjectType*. Describes entry point for fields to *read*
            data in your Schema.
        mutation (Optional[Type[ObjectType]]): Root mutation *ObjectType*. Describes entry point for
            fields to *create, update or delete* data in your API.
        subscription (Optional[Type[ObjectType]]): Root subscription *ObjectType*. Describes entry point
            for fields to receive continuous updates.
        directives (List[GraphQLDirective], optional): List of custom directives to include in
            GraphQL schema. Defaults to only include directives definved by GraphQL spec (@include
            and @skip) [GraphQLIncludeDirective, GraphQLSkipDirective].
        types (Optional[List[Type[ObjectType]]]): List of any types to include in schema that
            may not be introspected through root types.
        auto_camelcase (bool): Fieldnames will be transformed in Schema's TypeMap from snake_case
            to camelCase (preferred by GraphQL standard). Default True.
    """

After that problem will resolve

**Comment by qlibp** [comment] 2021-07-17 14:00
> > Thank you for the reply! I'm sorry I still don't understand how to do this, since I'm not defining the class `Schema` in my own code. All I'm doing is using `graphene.Schema`:
> > ![image](https://user-images.githubusercontent.com/17533713/84588223-d9d72500-ae25-11ea-8fc8-50cf67e5c550.png)
> > So I don't know where the type hint should go, since there's no `class Schema` in my code... Would you be so kind to tell me how you accomplished this? Did you subclass `graphene.Schema`? Thanks in advance :)
> 
> change the doc present in graphene/types/schema.py
> 
> replace:
> 
> **query (ObjectType): Root query _ObjectType_. Describes entry point for fields to _read_ data in your Schema.**
> 
> with
> 
> **query (Type[ObjectType]): Root query _ObjectType_. Describes entry point for fields to _read_ data in your Schema.**
> 
> After that problem will resolve

To be concrete, it's weird that pycharm will take the comment as a source for typing checking

**Comment by erikwrede** [comment] 2022-08-27 17:45
New issue for type hinting is #1454. Will start addressing this soon.

**Closed by erikwrede** 2022-08-27 17:45 UTC
