### ISSUE TITLE
Support Apollo Federation

### ISSUE THREAD

**Issue by salwator** [graphql-python/graphene#1081] opened 2019-10-04 10:15 UTC
Hi all,

We did implement GraphQL API for [Saleor](https://github.com/mirumee/saleor) using graphene and want to extend it using federation.

Supporting federation seems pretty straightforward, you need to provide _service type with _sdl_ field to get schema and and directives to mark _key_, _external_ and _required_ fields. There is an external package that partially implements it [here](https://github.com/erebus1/graphene-federation) but relying on additional package for core functionality is suboptimal.

Is anybody working on implementing this in graphene? Are there any known blockers? If not, we're fine with writing our own and contributing here.

Mentioning few guys to start discussion: @syrusakbary, @jkimbo, @ekampf, @dan98765

**Comment by fhennig** [comment] 2019-10-30 10:05
I'm interested in this too and so I've been following this.

[Here](https://github.com/graphql-python/graphene/issues/953#issuecomment-508481652) (#953) someone else already implemented something that apparently follows the federation specification.
Maybe @erebus1 and @anlauren would be interested in chiming in as well.

**Comment by anlauren** [comment] 2019-11-19 15:37
Yes there was a couple of discussions i have seen another one in stackoverflow, i wrote a hacky way to do so _around_ graphene, but i don't know the inside of the library enough to do this in there.
I was basically modifying the schema written by graphene to expose the right service description to the federation. The `graphene-federation` you mentioned started with this, now it could be good to get this inside graphene itself

**Comment by GiancarlosIO** [comment] 2020-02-11 18:46
:eyes:

**Comment by jkimbo** [comment] 2020-02-12 13:26
@salwator as far as I'm aware no one is actively working on this. Would be great to see though so if you get anything working do feedback here.

**Comment by Ambro17** [comment] 2020-03-30 00:46
Really interested in this issue if i can be of any help

**Comment by jottenlips** [comment] 2020-06-09 13:54
Would love to help as well

**Comment by troptop** [comment] 2020-07-23 09:32
I would like to help on this project 
I am using graphene-federation library and i find it very useful already
I know that a lot of new features will come up and it would be nice if we could integrate them (@internal key...)

I have created a login_required decorator for graphene-federation. I dont know if it is well done but at least it works.
see doc and code here:
https://github.com/troptop/graphene_federation_required_login

**Comment by cglacet** [comment] 2021-02-17 08:02
I'm wondering if any large project is using GraphQL with python backends, the more I look into it the more I feel there is no python community around GraphQL. Or maybe its just GraphQL as a whole that never really got adopted? Today it feels like a huge risk to use GraphQL for a large project, we've tested it on a small project and it's looking good (a monolithic app: postgres/sqlalchemy/graphene/starlette). But this issue and the lack of interest it got shows that it might not be suitable for larger projects (several "micro-service" teams working together). Maybe I'm just missing a part of this ecosystem?

Maybe what's missing is a large project to drive the development of the python graphql tools?

**Comment by chadfurman** [comment] 2021-07-12 00:08
Looks like this fork is better maintained for the graphene-federation stuff: https://github.com/loft-orbital/graphene-federation/tree/loft-master/graphene_federation

@BossGrand @jkimbo is there still interest in a PR for adding this to core?  Any thoughts on how you'd want someone to approach this, for the PR to get consideration / review / acceptance?

**Comment by jendrikjoe** [comment] 2022-05-16 14:39
Hey folks, I know this is quite stale, but I would like to pick this issue up 🙂 
The problem is that all downstream repos providing this are incompatible with graphene3, e.g. https://github.com/loft-orbital/graphene-federation/tree/loft-master/graphene_federation and as soon as the project is getting bigger it is virtually impossible to use graphene without federation.
Before I pick this, I would just like to make sure that the functionality is supposed to reside in the graphene repo.

**Comment by jendrikjoe** [comment] 2022-11-03 07:56
Given that there is https://github.com/graphql-python/graphene-federation now, I think this issue can be closed right? 🙂

**Comment by erikwrede** [comment] 2022-11-03 10:20
Graphene federation with support for graphene v3 is officially released in the `graphene-federation` repo of this organization! Federation v2 support is coming soon.

**Closed** 2022-11-03 10:20 UTC
Labels: 🙋 help wanted
